###
# Redirect to URL
###
GET http://localhost:8000/redirect?tenant_id=YOUR_TENANT_ID

###
# Create Connection
###
POST http://localhost:8000/create-connection HTTP/1.1
Content-Type: application/json

{
  "connection_id": "bod-connection",
  "name": "bod-customer-connector",
  "description": "web-deployed-gc"
}

###
# Create Schema
###
POST http://localhost:8000/create-schema
Content-Type: application/json

{
  "connection_id": "YOUR_CONNECTION_ID",
  "schema": {
    "YOUR_SCHEMA_KEY": "YOUR_SCHEMA_VALUE"
  }
}

###
# Push Content (commented out in main.py)
###
# POST http://localhost:8000/push-content
# Content-Type: application/json
#
# {
#   "connection_id": "YOUR_CONNECTION_ID",
#   "container_name": "YOUR_CONTAINER_NAME",
#   "blob_name": "YOUR_BLOB_NAME"
# }

#curl --location 'https://login.microsoftonline.com/5174ceb7-3102-4916-9c26-eb94f327f56d/oauth2/v2.0/token' \ --header 'Content-Type: application/x-www-form-urlencoded' \ --data-urlencode 'client_id=1153b495-9395-4350-929b-f195e9466370' \ --data-urlencode 'scope=https://graph.microsoft.com/.default' \ --data-urlencode 'client_secret=3no8Q~ugPXPEC1Cfn6FJkYICdb51Z8AWxHkzXcxuT' \ --data-urlencode 'grant_type=client_credentials'